#!/bin/sh
echo "pre_build"

# DEBUG
echo "SOURCE_BRANCH:    ${SOURCE_BRANCH}"
echo "SOURCE_COMMIT:    ${SOURCE_COMMIT}"
echo "COMMIT_MSG:       ${COMMIT_MSG}"
echo "DOCKER_REPO:      ${DOCKER_REPO}"
echo "DOCKERFILE_PATH:  ${DOCKERFILE_PATH}"
echo "DOCKER_TAG:       ${DOCKER_TAG}"
echo "IMAGE_NAME:       ${IMAGE_NAME}"

export STEAMAPPID=600760
curl -X GET "https://api.steamcmd.net/v1/info/${STEAMAPPID}" -o steaminfo.json
cat steaminfo.json
whereis jq

